# Generated by Django 5.0 on 2024-02-19 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agency_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('shortName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.IntegerField(max_length=10)),
                ('F_name', models.CharField(max_length=50)),
                ('L_name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=15)),
                ('capacity', models.IntegerField(max_length=100)),
                ('bus_class', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('Company', models.CharField(max_length=15)),
                ('Agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TicketBooking.agencies')),
            ],
        ),
        migrations.CreateModel(
            name='Distances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Distance', models.FloatField()),
                ('From', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='TicketBooking.locations')),
                ('To', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='TicketBooking.locations')),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('dep_time', models.TimeField()),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketBooking.locations')),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.FloatField()),
                ('Distance', models.FloatField()),
                ('date', models.DateField()),
                ('Arrival_loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='TicketBooking.locations')),
                ('Bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketBooking.buses')),
                ('Departure_loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='TicketBooking.locations')),
                ('Stops', models.ManyToManyField(through='TicketBooking.orders', to='TicketBooking.locations')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='Route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketBooking.routes'),
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketBooking.routes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketBooking.users')),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.IntegerField(max_length=100)),
                ('is_Booked', models.BooleanField()),
                ('name', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(max_length=30)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TicketBooking.bookings')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketBooking.buses')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction_id', models.CharField(max_length=30)),
                ('Method', models.CharField(max_length=30)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketBooking.bookings')),
            ],
        ),
    ]
