# Generated by Django 5.0 on 2024-03-04 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketBooking', '0002_alter_users_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Route',
        ),
        migrations.AlterField(
            model_name='buses',
            name='bus_class',
            field=models.CharField(choices=[('AC-sitting', 'AC-sitting'), ('AC-sleeper', 'AC-sleeper'), ('Luxury-sitting', 'Luxury-sitting'), ('Luxury-sleeper', 'Luxury-sleeper'), ('Express', 'Express'), ('Mini-Bus', 'Mini-Bus')], max_length=30),
        ),
        migrations.AlterField(
            model_name='seats',
            name='type',
            field=models.CharField(choices=[('normal', 'normal'), ('woman', 'woman'), ('child', 'child'), ('handicap', 'handicap'), ('elder-citizen', 'elder-citizen')], max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='type',
            field=models.CharField(choices=[('bus_operator', 'bus_operator'), ('admin', 'admin'), ('normal', 'normal'), ('driver', 'driver')], max_length=50),
        ),
        migrations.CreateModel(
            name='Paths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Distance', models.FloatField()),
                ('Time', models.TimeField()),
                ('From', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='TicketBooking.locations')),
                ('To', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='TicketBooking.locations')),
            ],
        ),
        migrations.CreateModel(
            name='stops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('Route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketBooking.routes')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketBooking.paths')),
            ],
        ),
        migrations.AlterField(
            model_name='routes',
            name='Stops',
            field=models.ManyToManyField(through='TicketBooking.stops', to='TicketBooking.paths'),
        ),
        migrations.DeleteModel(
            name='Distances',
        ),
        migrations.DeleteModel(
            name='orders',
        ),
    ]
