# Generated by Django 5.0 on 2024-03-15 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketBooking', '0005_alter_paths_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TicketBooking.bookings'),
        ),
    ]
