# Generated by Django 5.0 on 2024-03-30 19:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketBooking', '0008_stops_arrival_time_stops_departure_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='Amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='From',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_From', to='TicketBooking.locations'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='To',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_To', to='TicketBooking.locations'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seats',
            name='type',
            field=models.CharField(choices=[('normal', 'normal'), ('woman', 'woman')], max_length=30),
        ),
    ]
