# Generated by Django 5.0 on 2024-03-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketBooking', '0009_bookings_amount_bookings_from_bookings_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='departure_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='reaching_time',
            field=models.TimeField(null=True),
        ),
    ]
