# Generated by Django 5.0 on 2024-03-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketBooking', '0011_alter_bookings_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='To',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
