# Generated by Django 5.0 on 2024-03-30 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketBooking', '0012_alter_bookings_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='time',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
