# Generated by Django 5.0 on 2024-03-31 12:35

import TicketBooking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketBooking', '0015_remove_users_type_users_is_operator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='id',
            field=models.UUIDField(default=TicketBooking.models.generate_random_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
