# Generated by Django 5.0 on 2024-03-31 12:37

import TicketBooking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketBooking', '0016_alter_bookings_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='id',
            field=models.CharField(default=TicketBooking.models.generate_random_id, editable=False, max_length=15, primary_key=True, serialize=False),
        ),
    ]
