# Generated by Django 5.0 on 2024-03-31 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketBooking', '0018_alter_bookings_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='Bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TicketBooking.buses'),
        ),
    ]
